# SQLite version 3.x
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: flowv1
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: flowv1-test
  username: root
  password:
  pool: 5
  timeout: 5000